[2025-04-29T08:10:24.078+0000] {processor.py:156} INFO - Started process (PID=184) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:10:24.079+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:10:24.080+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:10:24.080+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:10:24.088+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:10:24.087+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-04-29T08:10:24.089+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:10:24.125+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.053 seconds
[2025-04-29T08:10:54.833+0000] {processor.py:156} INFO - Started process (PID=222) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:10:54.837+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:10:54.837+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:10:54.837+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:10:54.839+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:10:54.838+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-04-29T08:10:54.839+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:10:54.856+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T08:11:24.896+0000] {processor.py:156} INFO - Started process (PID=259) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:11:24.897+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:11:24.897+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:11:24.897+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:11:24.899+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:11:24.899+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-04-29T08:11:24.900+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:11:24.915+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.021 seconds
[2025-04-29T08:11:28.948+0000] {processor.py:156} INFO - Started process (PID=278) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:11:28.949+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:11:28.949+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:11:28.949+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:11:28.953+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:11:28.952+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-04-29T08:11:28.954+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:11:28.969+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.023 seconds
[2025-04-29T08:11:59.753+0000] {processor.py:156} INFO - Started process (PID=315) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:11:59.754+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:11:59.754+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:11:59.754+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:11:59.756+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:11:59.756+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-04-29T08:11:59.757+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:11:59.771+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.020 seconds
[2025-04-29T08:12:30.389+0000] {processor.py:156} INFO - Started process (PID=352) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:12:30.389+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:12:30.389+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:12:30.389+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:12:30.392+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:12:30.391+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-04-29T08:12:30.392+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:12:30.406+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.020 seconds
[2025-04-29T08:13:00.818+0000] {processor.py:156} INFO - Started process (PID=389) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:13:00.822+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:13:00.822+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:13:00.822+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:13:00.825+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:13:00.824+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-04-29T08:13:00.825+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:13:00.843+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.027 seconds
[2025-04-29T08:13:30.911+0000] {processor.py:156} INFO - Started process (PID=427) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:13:30.912+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:13:30.912+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:13:30.912+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:13:30.914+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:13:30.913+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-04-29T08:13:30.914+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:13:30.931+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.022 seconds
[2025-04-29T08:14:01.349+0000] {processor.py:156} INFO - Started process (PID=459) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:14:01.351+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:14:01.353+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:14:01.352+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:14:01.356+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:14:01.355+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-04-29T08:14:01.357+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:14:01.377+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.032 seconds
[2025-04-29T08:14:32.245+0000] {processor.py:156} INFO - Started process (PID=491) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:14:32.248+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:14:32.248+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:14:32.248+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:14:32.251+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:14:32.250+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 2, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-04-29T08:14:32.251+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:14:32.268+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T08:14:52.947+0000] {processor.py:156} INFO - Started process (PID=514) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:14:52.948+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:14:52.949+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:14:52.948+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:14:53.081+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:14:53.081+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:14:53.081+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:14:53.096+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.153 seconds
[2025-04-29T08:15:25.257+0000] {processor.py:156} INFO - Started process (PID=546) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:15:25.261+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:15:25.262+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:15:25.261+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:15:25.267+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:15:25.267+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:15:25.268+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:15:25.286+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.031 seconds
[2025-04-29T08:15:34.034+0000] {processor.py:156} INFO - Started process (PID=560) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:15:34.035+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:15:34.035+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:15:34.035+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:15:34.041+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:15:34.040+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:15:34.041+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:15:34.056+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.024 seconds
[2025-04-29T08:16:04.948+0000] {processor.py:156} INFO - Started process (PID=592) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:16:04.952+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:16:04.952+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:16:04.952+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:16:04.957+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:16:04.956+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:16:04.957+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:16:04.971+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T08:16:35.725+0000] {processor.py:156} INFO - Started process (PID=624) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:16:35.725+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:16:35.726+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:16:35.726+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:16:35.731+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:16:35.730+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:16:35.731+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:16:35.746+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.024 seconds
[2025-04-29T08:17:06.081+0000] {processor.py:156} INFO - Started process (PID=656) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:17:06.085+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:17:06.086+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:17:06.085+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:17:06.091+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:17:06.090+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:17:06.091+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:17:06.108+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.029 seconds
[2025-04-29T08:17:39.854+0000] {processor.py:156} INFO - Started process (PID=695) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:17:39.855+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:17:39.855+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:17:39.855+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:17:39.860+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:17:39.860+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:17:39.861+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:17:39.877+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T08:18:10.480+0000] {processor.py:156} INFO - Started process (PID=729) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:18:10.481+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:18:10.482+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:18:10.482+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:18:10.486+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:18:10.486+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:18:10.487+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:18:10.502+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.024 seconds
[2025-04-29T08:18:41.599+0000] {processor.py:156} INFO - Started process (PID=761) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:18:41.599+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:18:41.600+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:18:41.600+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:18:41.605+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:18:41.605+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:18:41.606+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:18:41.623+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.027 seconds
[2025-04-29T08:19:12.018+0000] {processor.py:156} INFO - Started process (PID=793) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:19:12.022+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:19:12.022+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:19:12.022+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:19:12.027+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:19:12.026+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:19:12.027+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:19:12.041+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.026 seconds
[2025-04-29T08:19:42.672+0000] {processor.py:156} INFO - Started process (PID=825) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:19:42.676+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:19:42.676+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:19:42.676+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:19:42.682+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:19:42.681+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:19:42.682+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:19:42.698+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.027 seconds
[2025-04-29T08:20:13.035+0000] {processor.py:156} INFO - Started process (PID=857) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:20:13.039+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:20:13.039+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:20:13.039+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:20:13.045+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:20:13.044+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:20:13.046+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:20:13.063+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.030 seconds
[2025-04-29T08:20:43.704+0000] {processor.py:156} INFO - Started process (PID=889) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:20:43.706+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:20:43.706+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:20:43.706+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:20:43.712+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:20:43.711+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:20:43.713+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:20:43.731+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.030 seconds
[2025-04-29T08:21:14.615+0000] {processor.py:156} INFO - Started process (PID=921) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:21:14.617+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:21:14.617+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:21:14.617+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:21:14.622+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:21:14.621+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:21:14.622+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:21:14.636+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.023 seconds
[2025-04-29T08:21:45.549+0000] {processor.py:156} INFO - Started process (PID=963) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:21:45.551+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:21:45.551+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:21:45.551+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:21:45.557+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:21:45.556+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:21:45.557+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:21:45.573+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.026 seconds
[2025-04-29T08:22:15.817+0000] {processor.py:156} INFO - Started process (PID=996) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:22:15.817+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:22:15.818+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:22:15.817+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:22:15.823+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:22:15.822+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:22:15.823+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:22:15.841+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.026 seconds
[2025-04-29T08:22:45.893+0000] {processor.py:156} INFO - Started process (PID=1028) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:22:45.898+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:22:45.898+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:22:45.898+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:22:45.903+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:22:45.902+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:22:45.903+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:22:45.921+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.029 seconds
[2025-04-29T08:22:58.077+0000] {processor.py:156} INFO - Started process (PID=1042) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:22:58.077+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:22:58.078+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:22:58.078+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:22:58.079+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:22:58.079+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:22:58.080+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:22:58.093+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.019 seconds
[2025-04-29T08:23:28.348+0000] {processor.py:156} INFO - Started process (PID=1074) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:23:28.349+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:23:28.350+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:23:28.350+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:23:28.351+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:23:28.351+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:23:28.352+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:23:28.368+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.023 seconds
[2025-04-29T08:23:58.509+0000] {processor.py:156} INFO - Started process (PID=1106) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:23:58.510+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:23:58.510+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:23:58.510+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:23:58.512+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:23:58.511+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:23:58.512+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:23:58.527+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.020 seconds
[2025-04-29T08:24:30.999+0000] {processor.py:156} INFO - Started process (PID=1138) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:24:31.003+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:24:31.003+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:24:31.003+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:24:31.005+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:24:31.004+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:24:31.005+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:24:31.020+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.023 seconds
[2025-04-29T08:25:01.993+0000] {processor.py:156} INFO - Started process (PID=1179) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:25:01.997+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:25:01.998+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:25:01.998+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:25:02.000+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:25:01.999+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:25:02.000+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:25:02.017+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.027 seconds
[2025-04-29T08:25:32.375+0000] {processor.py:156} INFO - Started process (PID=1202) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:25:32.376+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:25:32.376+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:25:32.376+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:25:32.378+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:25:32.377+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:25:32.378+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:25:32.396+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.023 seconds
[2025-04-29T08:26:03.071+0000] {processor.py:156} INFO - Started process (PID=1243) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:26:03.072+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:26:03.072+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:26:03.072+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:26:03.075+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:26:03.073+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:26:03.075+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:26:03.093+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.024 seconds
[2025-04-29T08:26:33.716+0000] {processor.py:156} INFO - Started process (PID=1276) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:26:33.719+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:26:33.720+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:26:33.720+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:26:33.722+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:26:33.721+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:26:33.722+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:26:33.740+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.026 seconds
[2025-04-29T08:27:04.645+0000] {processor.py:156} INFO - Started process (PID=1308) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:27:04.649+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:27:04.649+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:27:04.649+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:27:04.651+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:27:04.650+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:27:04.651+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:27:04.668+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T08:27:35.240+0000] {processor.py:156} INFO - Started process (PID=1341) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:27:35.240+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:27:35.240+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:27:35.240+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:27:35.242+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:27:35.241+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:27:35.242+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:27:35.263+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.026 seconds
[2025-04-29T08:28:05.797+0000] {processor.py:156} INFO - Started process (PID=1373) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:28:05.801+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:28:05.802+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:28:05.801+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:28:05.804+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:28:05.803+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:28:05.804+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:28:05.819+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.024 seconds
[2025-04-29T08:28:36.381+0000] {processor.py:156} INFO - Started process (PID=1405) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:28:36.385+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:28:36.386+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:28:36.386+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:28:36.388+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:28:36.387+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:28:36.388+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:28:36.404+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T08:29:06.872+0000] {processor.py:156} INFO - Started process (PID=1437) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:29:06.873+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:29:06.874+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:29:06.874+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:29:06.877+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:29:06.876+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:29:06.877+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:29:06.895+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.026 seconds
[2025-04-29T08:29:37.701+0000] {processor.py:156} INFO - Started process (PID=1469) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:29:37.705+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:29:37.705+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:29:37.705+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:29:37.708+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:29:37.707+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:29:37.708+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:29:37.725+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.026 seconds
[2025-04-29T08:30:08.616+0000] {processor.py:156} INFO - Started process (PID=1502) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:30:08.620+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:30:08.620+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:30:08.620+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:30:08.623+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:30:08.622+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:30:08.623+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:30:08.638+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.024 seconds
[2025-04-29T08:30:39.018+0000] {processor.py:156} INFO - Started process (PID=1534) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:30:39.018+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:30:39.019+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:30:39.019+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:30:39.021+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:30:39.020+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:30:39.021+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:30:39.038+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.023 seconds
[2025-04-29T08:31:09.997+0000] {processor.py:156} INFO - Started process (PID=1567) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:31:09.998+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:31:09.999+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:31:09.999+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:31:10.000+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:31:10.000+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:31:10.001+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:31:10.015+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.020 seconds
[2025-04-29T08:31:40.624+0000] {processor.py:156} INFO - Started process (PID=1608) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:31:40.625+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:31:40.625+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:31:40.625+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:31:40.627+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:31:40.626+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:31:40.627+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:31:40.643+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.022 seconds
[2025-04-29T08:32:11.098+0000] {processor.py:156} INFO - Started process (PID=1640) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:32:11.102+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:32:11.103+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:32:11.103+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:32:11.105+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:32:11.104+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:32:11.105+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:32:11.121+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.024 seconds
[2025-04-29T08:32:42.198+0000] {processor.py:156} INFO - Started process (PID=1672) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:32:42.199+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:32:42.200+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:32:42.200+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:32:42.202+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:32:42.201+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 49
    source = config["destinations"]["enviromnets"][0]["source"],
         ^
SyntaxError: invalid syntax
[2025-04-29T08:32:42.202+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:32:42.220+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T08:33:10.137+0000] {processor.py:156} INFO - Started process (PID=1704) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:33:10.139+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:33:10.139+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:33:10.139+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:33:10.141+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:33:10.140+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 51
    retry_delay = timedelta =(config["destinations"]["enviromnets"][0]["retry_delay"])
              ^
SyntaxError: invalid syntax
[2025-04-29T08:33:10.142+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:33:10.159+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.024 seconds
[2025-04-29T08:33:40.324+0000] {processor.py:156} INFO - Started process (PID=1736) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:33:40.325+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:33:40.326+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:33:40.326+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:33:40.328+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:33:40.327+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 51
    retry_delay = timedelta =(config["destinations"]["enviromnets"][0]["retry_delay"])
              ^
SyntaxError: invalid syntax
[2025-04-29T08:33:40.328+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:33:40.345+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.023 seconds
[2025-04-29T08:34:11.090+0000] {processor.py:156} INFO - Started process (PID=1768) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:34:11.093+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:34:11.094+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:34:11.094+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:34:11.096+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:34:11.095+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 51
    retry_delay = timedelta =(config["destinations"]["enviromnets"][0]["retry_delay"])
              ^
SyntaxError: invalid syntax
[2025-04-29T08:34:11.096+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:34:11.112+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T08:34:42.103+0000] {processor.py:156} INFO - Started process (PID=1800) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:34:42.104+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:34:42.104+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:34:42.104+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:34:42.107+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:34:42.106+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 51
    retry_delay = timedelta =(config["destinations"]["enviromnets"][0]["retry_delay"])
              ^
SyntaxError: invalid syntax
[2025-04-29T08:34:42.107+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:34:42.122+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.021 seconds
[2025-04-29T08:34:56.808+0000] {processor.py:156} INFO - Started process (PID=1823) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:34:56.809+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:34:56.810+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:34:56.810+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:34:56.812+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:34:56.811+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 51
    retry_delay = timedelta(minute = config["destinations"]["enviromnets"][0]["retry_delay"])
              ^
SyntaxError: invalid syntax
[2025-04-29T08:34:56.812+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:34:56.827+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.022 seconds
[2025-04-29T08:35:27.216+0000] {processor.py:156} INFO - Started process (PID=1855) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:35:27.220+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:35:27.221+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:35:27.221+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:35:27.224+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:35:27.223+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 51
    retry_delay = timedelta(minute = config["destinations"]["enviromnets"][0]["retry_delay"])
              ^
SyntaxError: invalid syntax
[2025-04-29T08:35:27.224+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:35:27.240+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.026 seconds
[2025-04-29T08:35:58.076+0000] {processor.py:156} INFO - Started process (PID=1887) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:35:58.080+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:35:58.080+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:35:58.080+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:35:58.082+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:35:58.081+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 51
    retry_delay = timedelta(minute = config["destinations"]["enviromnets"][0]["retry_delay"])
              ^
SyntaxError: invalid syntax
[2025-04-29T08:35:58.083+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:35:58.100+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.026 seconds
[2025-04-29T08:36:28.935+0000] {processor.py:156} INFO - Started process (PID=1919) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:36:28.938+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:36:28.939+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:36:28.939+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:36:28.941+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:36:28.940+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 51
    retry_delay = timedelta(minute = config["destinations"]["enviromnets"][0]["retry_delay"])
              ^
SyntaxError: invalid syntax
[2025-04-29T08:36:28.941+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:36:28.957+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.024 seconds
[2025-04-29T08:36:37.245+0000] {processor.py:156} INFO - Started process (PID=1931) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:36:37.246+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:36:37.246+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:36:37.246+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:36:37.248+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:36:37.247+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 51
    retry_delay = timedelta(minutes = config["destinations"]["environments"][0]["retry_delay"])
              ^
SyntaxError: invalid syntax
[2025-04-29T08:36:37.249+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:36:37.268+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.026 seconds
[2025-04-29T08:37:02.422+0000] {processor.py:156} INFO - Started process (PID=1956) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:37:02.426+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:37:02.426+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:37:02.426+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:37:02.434+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:37:02.433+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:37:02.435+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:37:02.454+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.035 seconds
[2025-04-29T08:37:32.783+0000] {processor.py:156} INFO - Started process (PID=1988) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:37:32.784+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:37:32.784+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:37:32.784+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:37:32.792+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:37:32.790+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:37:32.792+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:37:32.808+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.027 seconds
[2025-04-29T08:37:50.551+0000] {processor.py:156} INFO - Started process (PID=2011) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:37:50.555+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:37:50.555+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:37:50.555+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:37:50.561+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:37:50.560+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:37:50.561+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:37:50.576+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.027 seconds
[2025-04-29T08:38:21.116+0000] {processor.py:156} INFO - Started process (PID=2044) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:38:21.117+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:38:21.118+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:38:21.118+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:38:21.123+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:38:21.122+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:38:21.123+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:38:21.137+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.023 seconds
[2025-04-29T08:38:51.454+0000] {processor.py:156} INFO - Started process (PID=2076) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:38:51.454+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:38:51.455+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:38:51.455+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:38:51.460+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:38:51.459+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:38:51.460+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:38:51.474+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.023 seconds
[2025-04-29T08:39:21.538+0000] {processor.py:156} INFO - Started process (PID=2108) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:39:21.542+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:39:21.542+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:39:21.542+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:39:21.547+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:39:21.547+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:39:21.548+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:39:21.564+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.028 seconds
[2025-04-29T08:39:52.150+0000] {processor.py:156} INFO - Started process (PID=2140) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:39:52.151+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:39:52.151+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:39:52.151+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:39:52.156+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:39:52.155+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:39:52.156+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:39:52.170+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.022 seconds
[2025-04-29T08:40:24.098+0000] {processor.py:156} INFO - Started process (PID=2172) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:40:24.100+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:40:24.100+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:40:24.100+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:40:24.105+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:40:24.105+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:40:24.106+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:40:24.123+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.027 seconds
[2025-04-29T08:40:54.605+0000] {processor.py:156} INFO - Started process (PID=2213) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:40:54.606+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:40:54.607+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:40:54.607+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:40:54.613+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:40:54.612+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:40:54.613+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:40:54.630+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.027 seconds
[2025-04-29T08:41:24.913+0000] {processor.py:156} INFO - Started process (PID=2245) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:41:24.915+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:41:24.915+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:41:24.915+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:41:24.922+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:41:24.921+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:41:24.922+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:41:24.942+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.031 seconds
[2025-04-29T08:41:55.283+0000] {processor.py:156} INFO - Started process (PID=2277) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:41:55.284+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:41:55.284+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:41:55.284+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:41:55.289+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:41:55.289+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:41:55.289+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:41:55.304+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.023 seconds
[2025-04-29T08:42:25.734+0000] {processor.py:156} INFO - Started process (PID=2309) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:42:25.736+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:42:25.736+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:42:25.736+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:42:25.741+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:42:25.741+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:42:25.742+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:42:25.759+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.026 seconds
[2025-04-29T08:42:56.611+0000] {processor.py:156} INFO - Started process (PID=2341) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:42:56.615+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:42:56.615+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:42:56.615+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:42:56.620+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:42:56.619+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:42:56.620+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:42:56.634+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T08:43:26.936+0000] {processor.py:156} INFO - Started process (PID=2374) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:43:26.939+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:43:26.940+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:43:26.940+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:43:26.946+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:43:26.945+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:43:26.946+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:43:26.962+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.029 seconds
[2025-04-29T08:43:57.818+0000] {processor.py:156} INFO - Started process (PID=2406) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:43:57.821+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:43:57.822+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:43:57.822+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:43:57.827+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:43:57.826+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:43:57.827+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:43:57.842+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.027 seconds
[2025-04-29T08:44:28.780+0000] {processor.py:156} INFO - Started process (PID=2438) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:44:28.784+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:44:28.784+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:44:28.784+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:44:28.789+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:44:28.788+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:44:28.789+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:44:28.804+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.026 seconds
[2025-04-29T08:44:44.942+0000] {processor.py:156} INFO - Started process (PID=2461) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:44:44.943+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:44:44.943+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:44:44.943+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:44:44.949+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:44:44.948+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:44:44.950+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:44:44.966+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.027 seconds
[2025-04-29T08:45:15.125+0000] {processor.py:156} INFO - Started process (PID=2493) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:45:15.129+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:45:15.129+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:45:15.129+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:45:15.134+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:45:15.134+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:45:15.134+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:45:15.149+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.026 seconds
[2025-04-29T08:45:46.107+0000] {processor.py:156} INFO - Started process (PID=2525) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:45:46.110+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:45:46.111+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:45:46.111+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:45:46.117+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:45:46.116+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:45:46.117+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:45:46.134+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.030 seconds
[2025-04-29T08:46:16.440+0000] {processor.py:156} INFO - Started process (PID=2557) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:46:16.441+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:46:16.442+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:46:16.442+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:46:16.447+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:46:16.446+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:46:16.447+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:46:16.466+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.028 seconds
[2025-04-29T08:46:46.580+0000] {processor.py:156} INFO - Started process (PID=2589) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:46:46.581+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:46:46.581+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:46:46.581+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:46:46.586+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:46:46.586+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:46:46.587+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:46:46.601+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.023 seconds
[2025-04-29T08:47:11.915+0000] {processor.py:156} INFO - Started process (PID=2621) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:47:11.916+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:47:11.917+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:47:11.917+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:47:11.924+0000] {logging_mixin.py:117} INFO - Absolute path: /opt/airflow/ddp_airflow/src/copy_file.py
[2025-04-29T08:47:11.925+0000] {logging_mixin.py:117} INFO - The file does not exist.
[2025-04-29T08:47:11.934+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:47:11.933+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 58, in <module>
    python_callable = perform_copy_data,
NameError: name 'perform_copy_data' is not defined
[2025-04-29T08:47:11.934+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:47:11.953+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.041 seconds
[2025-04-29T08:47:42.794+0000] {processor.py:156} INFO - Started process (PID=2653) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:47:42.798+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:47:42.799+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:47:42.799+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:47:42.804+0000] {logging_mixin.py:117} INFO - Absolute path: /opt/airflow/ddp_airflow/src/copy_file.py
[2025-04-29T08:47:42.804+0000] {logging_mixin.py:117} INFO - The file does not exist.
[2025-04-29T08:47:42.808+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:47:42.808+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 58, in <module>
    python_callable = perform_copy_data,
NameError: name 'perform_copy_data' is not defined
[2025-04-29T08:47:42.809+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:47:42.831+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.040 seconds
[2025-04-29T08:48:13.659+0000] {processor.py:156} INFO - Started process (PID=2685) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:48:13.659+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:48:13.660+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:48:13.660+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:48:13.664+0000] {logging_mixin.py:117} INFO - Absolute path: /opt/airflow/ddp_airflow/src/copy_file.py
[2025-04-29T08:48:13.665+0000] {logging_mixin.py:117} INFO - The file does not exist.
[2025-04-29T08:48:13.671+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:48:13.669+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 58, in <module>
    python_callable = perform_copy_data,
NameError: name 'perform_copy_data' is not defined
[2025-04-29T08:48:13.671+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:48:13.687+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.030 seconds
[2025-04-29T08:48:43.854+0000] {processor.py:156} INFO - Started process (PID=2718) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:48:43.857+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:48:43.858+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:48:43.858+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:48:43.863+0000] {logging_mixin.py:117} INFO - Absolute path: /opt/airflow/ddp_airflow/src/copy_file.py
[2025-04-29T08:48:43.863+0000] {logging_mixin.py:117} INFO - The file does not exist.
[2025-04-29T08:48:43.868+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:48:43.867+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 58, in <module>
    python_callable = perform_copy_data,
NameError: name 'perform_copy_data' is not defined
[2025-04-29T08:48:43.868+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:48:43.885+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.034 seconds
[2025-04-29T08:48:48.054+0000] {processor.py:156} INFO - Started process (PID=2723) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:48:48.055+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:48:48.055+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:48:48.055+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:48:48.061+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:48:48.060+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:48:48.061+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:48:48.076+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.024 seconds
[2025-04-29T08:49:18.827+0000] {processor.py:156} INFO - Started process (PID=2755) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:49:18.828+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:49:18.829+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:49:18.829+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:49:18.833+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:49:18.833+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:49:18.834+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:49:18.848+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.023 seconds
[2025-04-29T08:49:49.406+0000] {processor.py:156} INFO - Started process (PID=2787) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:49:49.407+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:49:49.408+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:49:49.408+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:49:49.412+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:49:49.412+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:49:49.413+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:49:49.428+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T08:50:19.710+0000] {processor.py:156} INFO - Started process (PID=2819) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:50:19.714+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:50:19.714+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:50:19.714+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:50:19.720+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:50:19.719+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:50:19.720+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:50:19.735+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.027 seconds
[2025-04-29T08:50:50.750+0000] {processor.py:156} INFO - Started process (PID=2860) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:50:50.754+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:50:50.754+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:50:50.754+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:50:50.759+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:50:50.759+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:50:50.760+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:50:50.778+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.030 seconds
[2025-04-29T08:50:56.811+0000] {processor.py:156} INFO - Started process (PID=2865) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:50:56.811+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:50:56.812+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:50:56.811+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:50:56.820+0000] {logging_mixin.py:117} INFO - Absolute path: /opt/airflow/ddp_airflow/src/copy_file.py
[2025-04-29T08:50:56.820+0000] {logging_mixin.py:117} INFO - The file does not exist.
[2025-04-29T08:50:56.821+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:50:56.820+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 50, in <module>
    scheduler_interval = '@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2025-04-29T08:50:56.822+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:50:56.840+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.033 seconds
[2025-04-29T08:51:27.405+0000] {processor.py:156} INFO - Started process (PID=2897) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:51:27.409+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:51:27.409+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:51:27.409+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:51:27.414+0000] {logging_mixin.py:117} INFO - Absolute path: /opt/airflow/ddp_airflow/src/copy_file.py
[2025-04-29T08:51:27.414+0000] {logging_mixin.py:117} INFO - The file does not exist.
[2025-04-29T08:51:27.415+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:51:27.414+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 50, in <module>
    scheduler_interval = '@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2025-04-29T08:51:27.415+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:51:27.433+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.031 seconds
[2025-04-29T08:51:58.294+0000] {processor.py:156} INFO - Started process (PID=2936) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:51:58.296+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:51:58.296+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:51:58.296+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:51:58.300+0000] {logging_mixin.py:117} INFO - Absolute path: /opt/airflow/ddp_airflow/src/copy_file.py
[2025-04-29T08:51:58.301+0000] {logging_mixin.py:117} INFO - The file does not exist.
[2025-04-29T08:51:58.302+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:51:58.301+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 50, in <module>
    scheduler_interval = '@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2025-04-29T08:51:58.302+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:51:58.319+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.028 seconds
[2025-04-29T08:52:28.664+0000] {processor.py:156} INFO - Started process (PID=2970) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:52:28.668+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:52:28.669+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:52:28.668+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:52:28.675+0000] {logging_mixin.py:117} INFO - Absolute path: /opt/airflow/ddp_airflow/src/copy_file.py
[2025-04-29T08:52:28.675+0000] {logging_mixin.py:117} INFO - The file does not exist.
[2025-04-29T08:52:28.676+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:52:28.675+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 50, in <module>
    scheduler_interval = '@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2025-04-29T08:52:28.676+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:52:28.693+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.031 seconds
[2025-04-29T08:52:59.579+0000] {processor.py:156} INFO - Started process (PID=3002) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:52:59.580+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:52:59.580+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:52:59.580+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:52:59.584+0000] {logging_mixin.py:117} INFO - Absolute path: /opt/airflow/ddp_airflow/src/copy_file.py
[2025-04-29T08:52:59.584+0000] {logging_mixin.py:117} INFO - The file does not exist.
[2025-04-29T08:52:59.585+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:52:59.584+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 50, in <module>
    scheduler_interval = '@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2025-04-29T08:52:59.585+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:52:59.602+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.026 seconds
[2025-04-29T08:53:29.632+0000] {processor.py:156} INFO - Started process (PID=3034) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:53:29.635+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:53:29.635+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:53:29.635+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:53:29.639+0000] {logging_mixin.py:117} INFO - Absolute path: /opt/airflow/ddp_airflow/src/copy_file.py
[2025-04-29T08:53:29.639+0000] {logging_mixin.py:117} INFO - The file does not exist.
[2025-04-29T08:53:29.641+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:53:29.640+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 50, in <module>
    scheduler_interval = '@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2025-04-29T08:53:29.641+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:53:29.658+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.029 seconds
[2025-04-29T08:54:00.572+0000] {processor.py:156} INFO - Started process (PID=3065) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:54:00.575+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:54:00.576+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:54:00.576+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:54:00.580+0000] {logging_mixin.py:117} INFO - Absolute path: /opt/airflow/ddp_airflow/src/copy_file.py
[2025-04-29T08:54:00.580+0000] {logging_mixin.py:117} INFO - The file does not exist.
[2025-04-29T08:54:00.581+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:54:00.580+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 50, in <module>
    scheduler_interval = '@daily'
TypeError: __init__() got an unexpected keyword argument 'scheduler_interval'
[2025-04-29T08:54:00.581+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:54:00.598+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.029 seconds
[2025-04-29T08:54:22.854+0000] {processor.py:156} INFO - Started process (PID=3088) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:54:22.854+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:54:22.855+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:54:22.855+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:54:22.861+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:54:22.860+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:54:22.861+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:54:22.877+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T08:54:53.395+0000] {processor.py:156} INFO - Started process (PID=3120) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:54:53.399+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:54:53.400+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:54:53.400+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:54:53.406+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:54:53.406+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:54:53.407+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:54:53.424+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.031 seconds
[2025-04-29T08:55:23.580+0000] {processor.py:156} INFO - Started process (PID=3152) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:55:23.582+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:55:23.583+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:55:23.583+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:55:23.589+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:55:23.589+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:55:23.590+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:55:23.607+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.029 seconds
[2025-04-29T08:55:54.468+0000] {processor.py:156} INFO - Started process (PID=3184) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:55:54.469+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:55:54.469+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:55:54.469+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:55:54.474+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:55:54.474+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:55:54.475+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:55:54.490+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.024 seconds
[2025-04-29T08:56:20.712+0000] {processor.py:156} INFO - Started process (PID=3216) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:56:20.715+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:56:20.716+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:56:20.715+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:56:20.722+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:56:20.721+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:56:20.722+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:56:20.737+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.028 seconds
[2025-04-29T08:56:51.708+0000] {processor.py:156} INFO - Started process (PID=3248) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:56:51.709+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:56:51.709+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:56:51.709+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:56:51.714+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:56:51.714+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:56:51.715+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:56:51.730+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.024 seconds
[2025-04-29T08:57:22.509+0000] {processor.py:156} INFO - Started process (PID=3280) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:57:22.512+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:57:22.512+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:57:22.512+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:57:22.517+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:57:22.516+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:57:22.517+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:57:22.532+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T08:57:33.787+0000] {processor.py:156} INFO - Started process (PID=3294) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:57:33.787+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:57:33.788+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:57:33.788+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:57:33.794+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:57:33.793+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:57:33.794+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:57:33.811+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.027 seconds
[2025-04-29T08:58:04.756+0000] {processor.py:156} INFO - Started process (PID=3326) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:58:04.760+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:58:04.760+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:58:04.760+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:58:04.769+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:58:04.768+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:58:04.770+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:58:04.794+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.040 seconds
[2025-04-29T08:58:35.730+0000] {processor.py:156} INFO - Started process (PID=3367) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:58:35.734+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:58:35.735+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:58:35.735+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:58:35.745+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:58:35.745+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src'
[2025-04-29T08:58:35.746+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:58:35.765+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.038 seconds
[2025-04-29T08:58:44.854+0000] {processor.py:156} INFO - Started process (PID=3381) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:58:44.855+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:58:44.855+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:58:44.855+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:58:44.861+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:58:44.860+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:58:44.861+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:58:44.878+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.027 seconds
[2025-04-29T08:59:15.763+0000] {processor.py:156} INFO - Started process (PID=3414) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:59:15.766+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:59:15.767+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:59:15.767+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:59:15.771+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:59:15.771+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:59:15.772+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:59:15.788+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.028 seconds
[2025-04-29T08:59:37.657+0000] {processor.py:156} INFO - Started process (PID=3437) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:59:37.661+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:59:37.661+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:59:37.661+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:59:37.668+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:59:37.667+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from ddp_airflow.src_1.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'ddp_airflow'
[2025-04-29T08:59:37.668+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:59:37.686+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.031 seconds
[2025-04-29T08:59:48.107+0000] {processor.py:156} INFO - Started process (PID=3451) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:59:48.107+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T08:59:48.108+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:59:48.108+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:59:48.113+0000] {logging_mixin.py:117} INFO - [2025-04-29T08:59:48.112+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src_1.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src_1'
[2025-04-29T08:59:48.113+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T08:59:48.129+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T09:00:18.532+0000] {processor.py:156} INFO - Started process (PID=3483) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T09:00:18.533+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T09:00:18.533+0000] {logging_mixin.py:117} INFO - [2025-04-29T09:00:18.533+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T09:00:18.538+0000] {logging_mixin.py:117} INFO - [2025-04-29T09:00:18.537+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src_1.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src_1'
[2025-04-29T09:00:18.538+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T09:00:18.553+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T09:00:48.936+0000] {processor.py:156} INFO - Started process (PID=3516) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T09:00:48.940+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T09:00:48.940+0000] {logging_mixin.py:117} INFO - [2025-04-29T09:00:48.940+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T09:00:48.946+0000] {logging_mixin.py:117} INFO - [2025-04-29T09:00:48.945+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src_1.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src_1'
[2025-04-29T09:00:48.946+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T09:00:48.962+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.028 seconds
[2025-04-29T09:01:19.658+0000] {processor.py:156} INFO - Started process (PID=3548) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T09:01:19.658+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T09:01:19.659+0000] {logging_mixin.py:117} INFO - [2025-04-29T09:01:19.658+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T09:01:19.664+0000] {logging_mixin.py:117} INFO - [2025-04-29T09:01:19.663+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src_1.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src_1'
[2025-04-29T09:01:19.664+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T09:01:19.681+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.025 seconds
[2025-04-29T09:01:50.642+0000] {processor.py:156} INFO - Started process (PID=3580) to work on /opt/airflow/dags/copy_db_dag.py
[2025-04-29T09:01:50.646+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/copy_db_dag.py for tasks to queue
[2025-04-29T09:01:50.646+0000] {logging_mixin.py:117} INFO - [2025-04-29T09:01:50.646+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T09:01:50.652+0000] {logging_mixin.py:117} INFO - [2025-04-29T09:01:50.651+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/copy_db_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/copy_db_dag.py", line 4, in <module>
    from src_1.copy_file import perform_copy_data
ModuleNotFoundError: No module named 'src_1'
[2025-04-29T09:01:50.652+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/copy_db_dag.py
[2025-04-29T09:01:50.668+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/copy_db_dag.py took 0.028 seconds
